[텐서(TENSOR)](https://tutorials.pytorch.kr/beginner/basics/tensorqs_tutorial.html#)

## 텐서

In [1]:
"""
텐서
    배열, 행렬과 매우 유사한 특수한 자료구조
    PyTorch에서는 텐서를 사용하여 모델의 출력와 입력, 매개변수들을 부호화
    NumPy의 ndarray와 유사하나 하드웨어 가속기에서 실행
    자동 미분에 최적화
"""
import torch
import numpy as np

## 텐서 초기화

In [17]:
# 데이터로부터 직접 생성
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [18]:
# NumPy 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [19]:
# 다른 텐서로부터 생성
# 재정의하지 않는다면 인자로 주어진 텐서의 속성(모양, 자료형)을 유지
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8313, 0.9545],
        [0.8036, 0.5701]]) 



In [20]:
# 무작위 또는 상수 값을 사용하여 텐서 생성
# shpae : 텐서의 차원 나타내는 튜플
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6932, 0.5611, 0.9560],
        [0.9035, 0.3642, 0.0171]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성

In [9]:
"""
텐서의 속성
    텐서의 모양(shape)
    텐서의 자료형(datatype)
    어느 장치에 저장되는지
"""

tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 텐서 연산

In [10]:
"""
전치, 인덱싱, 슬라이싱, 수학 계산, 선형 대수, 샘플링, ...
기본적으로 텐서는 CPU에 생성됨
    -> .to 메소드를 사용하여 GPU로 텐서를 명시적으로 이동
"""

# GPU 존재시에 텐서 이동
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [21]:
# 표준 인덱싱 및 슬라이싱
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [22]:
# 텐서 합치기 : torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [25]:
# 산술 연산

# 행렬 곱 계산
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)

# 출력 텐서를 y3로 지정
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱 계산
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)

# 출력 텐서를 z3로 지정
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [28]:
# 단일 요소 텐서
# 요소가 하나인 텐서의 경우, item()을 이용해 숫자 값으로 변환 가능
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [30]:
# 바꿔치기(in-place) 연산
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

# 메모리를 절약하지만 기록이 삭제되어 도함수 계산시 문제 발생 가능

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


## NumPy 변환

In [32]:
# 텐서를 NumPy로
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

# CPU상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에 하나를 변경하면
# 다른 하나도 변경된다

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [33]:
# 텐서의 변경 사항이 NumPy 배열에 반영
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [34]:
# Numpy를 텐서로
n = np.ones(5)
t = torch.from_numpy(n)

In [35]:
# NumPy 배열 변경 사항이 텐서에 반영
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
